version: '3'

services:
  instagram-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../data:/app/data
    restart: unless-stopped
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - INSTAGRAM_TARGET_ACCOUNT=your_target_account
      - INSTAGRAM_USERNAME=your_instagram_username
      - INSTAGRAM_PASSWORD=your_instagram_password